version: '3'
services:
  app:
    container_name: sportfolios_app_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      network: 'host'
    volumes:
      - '.:/sportfolios'
      - './node_modules:/sportfolios/node_modules'
      - './.next:/sportfolios/.next'
    ports:
      - 3000:3000
    # make container listen to file changes
    environment:
      - CHOKIDAR_USEPOLLING=true
    cpus: 1.00
    mem_limit: 3gb
