// // // export { default as Accordion } from './Accordion';
// // // export { default as AccordionDnD } from './AccordionDnD';
// // // export { default as Autocomplete } from './Autocomplete';
// // // export { default as AddressSearchInput } from './AddressSearchInput';
// // // export { default as Avatar } from './Avatar';
// // // export { default as BottomNavigation } from './BottomNavigation';
// // // export { default as Button } from './Button';
// // // export { default as Card } from './Card';
// // // export { default as CardMedia } from './CardMedia';
// // // export { default as CheckBox } from './CheckBox';
// // // export { default as Chip } from './Chip';
// // // export { default as Collapse } from './Collapse';
// // // export { default as ComponentFactory } from './ComponentFactory';
// // // export { default as Container } from './Container';
// // // export { default as ContainerBottomFixed } from './ContainerBottomFixed';
// // // export { default as Dialog, AlertDialog } from './Dialog';
// // // export { default as DownloadReportDialog } from './Dialog/DownloadReportDialog';
// // // export { default as DnDSimpleList } from './DnDSimpleList';
// // // export { default as EntityCreate } from './EntityCreate';
// // // export { default as EntityList } from './EntityList';
// // // export { default as FacebookLoginButton } from './FacebookLoginButton';
// // // export { default as FeatureContainer } from './FeatureContainer';
// // // export { default as FormDialog } from './FormDialog';
// // export { default as Icon } from './Icon';
// // // export { default as IconButton } from './IconButton';
// // // export { default as IgContainer } from './IgContainer';
// // // export { default as ImageCard } from './ImageCard';
// // // export { default as Input } from './Input';
// // // export { default as List } from './List';
// // // export { default as LoadingSpinner } from './LoadingSpinner';
// // // export { default as MailToButton } from './MailToButton';
// // // export { default as MessageAndButtons } from './MessageAndButtons';
// // // export { default as MultiSelect } from './MultiSelect';
// // // export { default as MyGames } from './MyGames';
// // // export { default as Paper } from './Paper';
// // // export { default as PersonSearchList } from './SearchList/PersonSearchList';
// // // export { default as ProfileChip } from './ProfileChip';
// // // export { default as RadioGroup } from './RadioGroup';
// // // export { default as SearchInput } from './SearchInput';
// // // export { default as SearchList } from './SearchList';
// // // export { default as Select } from './Select';
// // // export { default as SnackBar } from './SnackBar';
// // // export { default as SpeedDial } from './SpeedDial';
// // // export { default as Stepper } from './Stepper';
// // // export { default as StepperWithHooks } from './StepperWithHooks';
// // // export { default as Tab } from './Tab';
// // // export { default as Table } from './Table';
// // // export { default as Tabs } from './Tabs';
// // // export { default as TeamSearchList } from './SearchList/TeamSearchList';
// // // export { default as TextField } from './TextField';

import loadable from '@loadable/component';

export const Accordion = loadable(() => ìmport('./Accordion'));
export const AccordionDnD = loadable(() => import('./AccordionDnD'));
export const AlertDialog = loadable(() => import('./Dialog/AlertDialog'));
export const Autocomplete = loadable(() => import('./Autocomplete'));
export const AddressSearchInput = loadable(() => import('./AddressSearchInput'));
export const Avatar = loadable(() => import('./Avatar'));
export const BottomNavigation = loadable(() => import('./BottomNavigation'));
export const Button = loadable(() => import('./Button'));
export const Card = loadable(() => import('./Card'));
export const CardMedia = loadable(() => import('./CardMedia'));
export const CheckBox = loadable(() => import('./CheckBox'));
export const Chip = loadable(() => import('./Chip'));
export const Collapse = loadable(() => import('./Collapse'));
export const ComponentFactory = loadable(() => import('./ComponentFactory'));
export const Container = loadable(() => import('./Container'));
export const ContainerBottomFixed = loadable(() => import('./ContainerBottomFixed'));
export const Dialog = loadable(() => import('./Dialog'));
export const DownloadReportDialog = loadable(() => import('./Dialog/DownloadReportDialog'));
export const DnDSimpleList = loadable(() => import('./DnDSimpleList'));
export const EntityCreate = loadable(() => import('./EntityCreate'));
export const EntityList = loadable(() => import('./EntityList'));
export const FacebookLoginButton = loadable(() => import('./FacebookLoginButton'));
export const FeatureContainer = loadable(() => import('./FeatureContainer'));
export const FormDialog = loadable(() => import('./FormDialog'));
export const Icon = loadable(() => import('./Icon'));
export const IconButton = loadable(() => import('./IconButton'));
export const IgContainer = loadable(() => import('./IgContainer'));
export const ImageCard = loadable(() => import('./ImageCard'));
export const Input = loadable(() => import('./Input'));
export const List = loadable(() => import('./List'));
export const LoadingSpinner = loadable(() => import('./LoadingSpinner'));
export const MailToButton = loadable(() => import('./MailToButton'));
export const MessageAndButtons = loadable(() => import('./MessageAndButtons'));
export const MultiSelect = loadable(() => import('./MultiSelect'));
export const MyGames = loadable(() => import('./MyGames'));
export const Paper = loadable(() => import('./Paper'));
export const PersonSearchList = loadable(() => import('./SearchList/PersonSearchList'));
export const ProfileChip = loadable(() => import('./ProfileChip'));
export const RadioGroup = loadable(() => import('./RadioGroup'));
export const SearchInput = loadable(() => import('./SearchInput'));
export const SearchList = loadable(() => import('./SearchList'));
export const Select = loadable(() => import('./Select'));
export const SnackBar = loadable(() => import('./SnackBar'));
export const SpeedDial = loadable(() => import('./SpeedDial'));
export const Stepper = loadable(() => import('./Stepper'));
export const StepperWithHooks = loadable(() => import('./StepperWithHooks'));
export const Tab = loadable(() => import('./Tab'));
export const Table = loadable(() => import('./Table'));
export const Tabs = loadable(() => import('./Tabs'));
export const TeamSearchList = loadable(() => import('./SearchList/TeamSearchList'));
export const TextField = loadable(() => import('./TextField'));
